{% set version = "1.3.4" %}
{%set sha256 = "37b09353267920729b86650418c527114cce31e9184cf32c0a3d8ac0fe898baa" %}
{% set name = "constructor" %}
{% set branch = "master" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ branch }}.tar.gz
  url: https://github.com/cryoem/{{ name }}/archive/{{ branch }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install

requirements:
  build:
    - python

  run:
    - python
    - libconda
    - pillow >=3.1  # [win]
    - nsis          # [win]

test:
  imports:
    - constructor

  commands:
    - constructor --help

about:
  home: http://github.com/conda/constructor
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: create installer from conda packages
