travis:
  secure:
    BINSTAR_TOKEN: j5kzn202BOFSntw6Jqp2HoYXkT2zierOif1hFrerGqDFFyj4iwIzbt1s8K95xDkm5YfR586TIUpLEdjAKeMev/U03jxMtQ2dDMGqgLN8SyqU5S/rG16MyjGrLc8V1RnFkvI7BIEhL1DPR0qkmnah44uvIZbMT0RN1e85q1OBHx6n7aPXkgF8qOSU4wV98OwDfu1YJlPQuj8krNr0DJyV+qHu/yX8SIvHpAIm0tAKDRougR9Q7JnyHATG2cqahJUAZxPereuu3mZnfyS0PJlvA7prCgl7GuwNtJq2b8A1YpmfM5bBETQa+pZlIfOa9q3lYaZE7C+3PlXIG/99CvE65eFGOl8N/L+9BJkXuYRl8nRsqUTOLLQLtYBy8jl+aZQxwdSXwX5JKvKGQJYg3BGRNxp4CvMsULL+ROvxwHjcFDKINgwCTajX0ijSL0/NButw8bcsugVjfVy9xOpGnKOLmGJJJ7cqrxFMsJaHpm1WW2yF4hhuYMBWVdkXx3Iy0ytRfQ6vnH2X7WEmsaX3lMhZcNPM7yIN3iMW+9OkkDMgz9jXWBcF/IgpEV+QoB0pY1Cf49Ek4MSR+gBYMGmGl7uwrtBh/y+A/BhIE4peU6NQMaqI9iSQ/TUfoUO0AhSzJj8JMFuUr67ugVkbNdKBC9Hqyd5DXaDyJvzDBafSe2IIuMU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC

channels:
  targets:
  - [cryoem, main]

github:
  user_or_org: cryoem
  repo_name: constructor-feedstock
