channels:
  targets:
  - [cryoem, main]

github:
  user_or_org: cryoem
  repo_name: constructor-feedstock

provider:
  linux: circle
  osx: travis
  win: appveyor

azure:
  build_id: blank

travis:
  secure:
    BINSTAR_TOKEN: gHGPNsZY0Jv7HNH1Zma7x/fTIzogxYiPvx+m9HJiGW2CtMhQFeusx+5DWO+PTAeu/dhff5TK/eJt63zoAQ0kdvUtLGoG86frilcIDR1hdSrzZoosI4Qsti35VbEVth2yhYSQFyjDhEFwKLBaQrhW69ukc8uHSnhsz924IZa3NvOrRTJXJKs2DsVwUnamRSgEqpMPzxVbE3Qawo5U6bhVDR51iFjwDZUjY0Prvx2vanO9nWIlyho2uYFRBUfQWkf67SQEcmq0ngV+kA8g5GHbV8At1d88fT7dUPyL6kYqnWCQbLVAmpoX5pjk0tu4bJyW24YU9CcLLE859hc1+hMot/2tOGh6dPjCu4NcBwKvSVIPB67u1PhNuhmjgcUqP6wf5y7RY/7QnS3P6jsYgPleQu3xQrVSTT2e2x55+TXYAAY5tcwQ9C0jKKhB3NFVHZz1b4HWzy+1mTqKH2NSNl5p7AqRwBoMvpvYQYIA3qzK+TfgSXmnt21rDfKUErwkjPIXyAHtGUdscavoQZFuc0rQ2X95Nzgi9MC8+w/UUJbrZ8ySqhJqEsuWeo0NfgRRkGb4D5zrISRDDp+GbazY8yLfeB/oEkboU7Sd4bzVO1TTse1BVihvnMLQ7ARAvSyqTMc/lq4MBKZGHJuUpxvCcr+1bHKrHjpLaymOumu70KYkb4s=
appveyor:
  secure:
    BINSTAR_TOKEN: hhS98dVbKVMiq1d7IEUyMCfA9Be1YSA2+BfDYf+1wwLYdOoWLWVaehGr6/mjqeAv
