channels:
  targets:
  - [cryoem, main]

github:
  user_or_org: cryoem
  repo_name: constructor-feedstock

travis:
  secure:
    BINSTAR_TOKEN: RsESHNPUlBXwwiU9byOu5+SJLM61MybXBm5W1fYRBLyrq9ZyeF6I9Iu1HHkOsh4EBuhib+lfaylG9b46Slia8/9ntfyHVsQmm+M0PSsuMAW42+/2iyhJUba2/hTTjROQ8jhtuZNzYjcGeglO2tL5ATKUiB4kd2gjgSCV+sYn/d5yNAvax548nULaJUhQM5zQb2OnipiX7bm3JA6ecigJTtWJqTlUGTUfmKxYb+YRw0D9PDIXIH31nRHUtJzHy1RzVqUb4E5asIJjUYG7Z/8dXNzPjnj0MInGbjQZcCHxC0x2+6P3kmzF8liLSe8hz0hQP2Qb5HReYfpFW+FiaKuAFeY6wr09hrGM9RS0qqVf/sAhgXnbis3i/1YT6jYZRSrIjhHOe6Bx63pIo/DzUr5gqehQ0w4Iqa/jLUsxNWXauQvaJTQ0SOpdQ6yn6aVJ3FikQy5OxDE9VJ+pQVXqNUwWzLKOyC5Bd9YQRZkZSTAWV4iN5nFO71JZtZ+Z6XRNu60slTc0UrRRo5njBqRVoZ2ADmKLzw7QAY6bV6jlvntbzpMw269NFOuyXtSlYYEChNcNgljrgr9hsvCUGRU749xy7gN/TGUfNrn7VD3gGZUJt8swZFulDzzhXexq1a6f0omFLlDVM46ZYtbi7iElU6Y1SjNa8MZKypgaYK//E0aPupo=
appveyor:
  secure:
    BINSTAR_TOKEN: DytmJU8Iq1lbelvMvcsTjak25U7QPYCTMr8QmMzqRw21AmRfcLQhfuNPZtjH13q9
