channels:
  targets:
  - [cryoem, main]

github:
  user_or_org: cryoem
  repo_name: constructor-feedstock

provider:
  linux: circle
  osx: travis
  win: appveyor

azure:
  build_id: blank

travis:
  secure:
    BINSTAR_TOKEN: gLCh8aog7LlHGMPKGaRld6a/q7wnuiQEAMaHo15rNCCBbzaZqkGmd+36zmuF5zmtOHeLos30yy5K0mCjZZefDpLUsRsDbZDY3RMEf1GxpZ+ATDxdapkXT1B2rIr04yWIKorR0+Gs5CksJBByloSs2/CDL33Z3uK1n5L4kPjXeGFAdmBJSYbDfgg1Rr5Yiszb5EGWhhq0NMtI7GPlPwc033u9N7kCNAEEVFKqvBe1qHppIS8x8A5qfW4zRFrqn1t0cwjRveZiqFEP8fWxil7BfBNnUHcEk4mQjHA4IfjumXLDJiX9i8GYNoP9bAoKVo6XhPO07C5aHsRWf69DSUdbEApnD0paPsOmi0GV0/nFgg5gShnQweij9lEUWYyFv3nEQR0lXg64T14hIOpr/eylPfKkw00iyQlDiPuf5eXYYfDjjgdLCq37P4q04GtLolM9BYJq0GNA5zb4i2xuwD1OW4xY6HuwWspcz8FhFNI6oeEfu6/JRCTwKRrnqpFs/4S0UeNN3krQyjughDkhztcZVC68JEsL5c2z2yCZvq1ivsNQHdf5xo8kqfJoXYF+g6ZdVwzucp3AxLRJ51c/ZYBus6cqglZY8jxu0BzYq7zl+1YqudUCZeOr8jU25XLOcWGpIFpkwZVFFkpHxO0lQqu37ueXhKFYGyJXZoWL1NptEmQ=
appveyor:
  secure:
    BINSTAR_TOKEN: hhS98dVbKVMiq1d7IEUyMCfA9Be1YSA2+BfDYf+1wwLYdOoWLWVaehGr6/mjqeAv
