travis:
  secure:
    BINSTAR_TOKEN: mT3SUumUHbugrrnf5xqGCIyvE5GepO6QjncesTyD7MptjKFnXh5KFCXSLjjaoP4X5C+1TQFL/wgw2wQlEvcAx4kCoItCPwqqd5vJWhtjx3+wMuhKZjx5Jg/4Aj5rR6F5CtTT9PwysUjhh7dmShGZO8NhkqyFdteFPtifeR8mdYHeedWm9ggRJng5XrIRowsgiKFJIm6B6eDGFm5BVBjZICuf6potDam4sEYSgz9yvCi/MqSqKFo3RZA7NS14vegxxUvCafi2EmdJ6SE5hsZwQ9YZvR+0k7x13beZeVVx9BqUcLlIyeZG92TknY5Byt6Fs4gqN5B0LgyiEmE2P80A5UTWFiAnloFTNwiT+H9oTCNwKCzOn85sErqBuk+9BiFEb35UXuxuCOceX8RWbp7Rfkyn3a3UaENnYHyiHe94TyQb+U4xUjheJTn5avDF9DqZAth2FvzzhjC1xSn+pIjuc4wzvGDnoMIQi3XhP5aUEd2cWnYZrv5U5kmqTCekuvEyyQ6FRlfGO5KPLG2DU1fMf+dU4nZF8N0xadlYGWhaTJPfsSDWbj3TXNRwFyebZzeSybnibap3seseBYJpiWDeIgf4ZJR4o0Ar2R6Z0068Gpt4YySlB2rKkdLnmq2tfNA91J+0jFXsCy2LfqqT1/783Uphk3kmBmvpF6kJ11Ig2ig=
appveyor:
  secure:
    BINSTAR_TOKEN: OcAUZlpSDgQtX8QAIX7qr8iZhsrOWwlmuyDECE7wAYBRlvXIBJ7BbXhX/Fmz4Oib

channels:
  targets:
  - [cryoem, main]

github:
  user_or_org: cryoem
  repo_name: constructor-feedstock
